/**
 * Downloads the Poppins web fonts into frontend/public/fonts and writes the
 * @font-face stylesheet that serves them.
 *
 * The application must not request fonts from Google at runtime: that makes every
 * user's browser call a third party on each page load, which leaks their IP and the
 * referring host, and it breaks the interface on a restricted or air-gapped network —
 * both unacceptable for a deployment on Seplat's own infrastructure.
 *
 * Run only when the font needs refreshing (a new weight, or a Google Fonts revision):
 *
 *   node frontend/scripts/fetch-fonts.mjs
 *
 * The downloaded files are committed, so a normal build and a normal install need no
 * network access to Google at all.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
// Kept under src/ rather than public/ so Vite rewrites the URLs at build time.
// The build uses a relative base so it can be served from a sub-path; absolute
// /fonts/... URLs would 404 there.
const FONT_DIR = path.resolve(HERE, '../src/assets/fonts');
const CSS_OUT = path.resolve(HERE, '../src/fonts.css');

const WEIGHTS = [400, 500, 600, 700, 800];
// Devanagari is offered by Google for Poppins but is not used by this interface.
const SUBSETS = ['latin', 'latin-ext'];

// Google serves woff2 only to browsers that advertise support for it.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

async function main() {
  const url = `https://fonts.googleapis.com/css2?family=Poppins:wght@${WEIGHTS.join(';')}&display=swap`;
  const css = await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => {
    if (!r.ok) throw new Error(`Google Fonts returned ${r.status}`);
    return r.text();
  });

  await mkdir(FONT_DIR, { recursive: true });

  // Each face is preceded by a subset comment: /* latin */ @font-face { ... }
  const faces = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g)];
  if (faces.length === 0) throw new Error('Could not parse any @font-face blocks.');

  const blocks = [];
  let downloaded = 0;

  for (const [, subset, body] of faces) {
    if (!SUBSETS.includes(subset)) continue;

    const weight = body.match(/font-weight:\s*(\d+)/)?.[1];
    const src = body.match(/url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/)?.[1];
    const range = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim();
    if (!weight || !src) continue;

    const filename = `poppins-${weight}-${subset}.woff2`;
    const bytes = Buffer.from(
      await fetch(src, { headers: { 'User-Agent': UA } }).then((r) => {
        if (!r.ok) throw new Error(`${filename}: ${r.status}`);
        return r.arrayBuffer();
      }),
    );
    await writeFile(path.join(FONT_DIR, filename), bytes);
    downloaded += 1;
    console.log(`  ${filename}  ${(bytes.length / 1024).toFixed(1)} KB`);

    blocks.push(
      [
        '@font-face {',
        "  font-family: 'Poppins';",
        '  font-style: normal;',
        `  font-weight: ${weight};`,
        '  font-display: swap;',
        `  src: url('./assets/fonts/${filename}') format('woff2');`,
        range ? `  unicode-range: ${range};` : null,
        '}',
      ]
        .filter(Boolean)
        .join('\n'),
    );
  }

  const header = [
    '/*',
    ' * Generated by frontend/scripts/fetch-fonts.mjs — do not edit by hand.',
    ' *',
    ' * Poppins is served from this application rather than from Google so that no',
    ' * user browser makes a third-party request on page load, and so the interface',
    ' * renders correctly on a network with no outbound access.',
    ' *',
    ' * Poppins is licensed under the SIL Open Font License 1.1.',
    ' */',
    '',
  ].join('\n');

  await writeFile(CSS_OUT, `${header}${blocks.join('\n\n')}\n`);
  console.log(`\n${downloaded} font files -> frontend/src/assets/fonts`);
  console.log(`stylesheet -> frontend/src/fonts.css`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
