export interface HelpTopic {
  id: string;
  question: string;
  answer: string[];
  tag: 'Data' | 'Roles' | 'Reports' | 'Impact';
}

export const HELP_TOPICS: HelpTopic[] = [
  {
    id: 'reach-vs-impact',
    tag: 'Impact',
    question: 'What is the difference between reach and impact?',
    answer: [
      'Reach counts everyone a programme interacted with — people who applied, attended, were screened, or live inside a catchment area. Impact counts only those who actually received the intervention.',
      'They are reported as two separate figures on purpose. The STEAM programme is the clearest example: 120,000 students applied for a scholarship and 48 received one. All 120,000 were reached; 48 were impacted. Reporting the full 120,000 as people impacted would overstate the result by a factor of 2,500.',
      'Every programme page shows both figures, the conversion rate between them, and a note explaining what separates the two for that specific programme. The Executive Dashboard shows the portfolio totals and a breakdown by pillar.',
      'Reach is not a lesser number — it is the honest measure of scale, and the gap between reach and impact is itself useful: 1,640 applications for 83 YEP training places is direct evidence of unmet demand.',
    ],
  },
  {
    id: 'custom-fields',
    tag: 'Data',
    question: 'Can we add our own fields to a programme?',
    answer: [
      'Yes. Each programme page has a "Questions about this programme" section where an executive or project manager can record a question stakeholders keep asking, along with the answer and its source.',
      'The point is to stop the same question generating a fresh ad-hoc report each time. If the board repeatedly asks what share of scholarships went to host-community students, that answer lives on the programme page and appears in the programme\u2019s exported report.',
      'Every answer carries a source and a last-updated stamp, on the same rule as impact figures — a number without a source is not reportable.',
    ],
  },
  {
    id: 'lens-toggle',
    tag: 'Data',
    question: 'What does the Local / Global lens toggle on the Executive Dashboard actually do?',
    answer: [
      'It re-frames the same underlying dataset for two different audiences, rather than filtering to different data.',
      'Local shows figures the way Nigerian regulators expect them: NCDMB local content percentages, PIA Host Community Development Trust spend, NUPRC host-community obligations.',
      'Global shows the same activity translated into GRI Standards, IFRS S1/S2 (ISSB) sustainability disclosures, and UN SDG contributions — the language international investors and ESG raters expect.',
      'Both shows every tag side by side so you can see how one project satisfies both audiences at once. Switching lenses changes the KPI subtitles, the budget-breakdown caption, and which tags appear on each outcome row.',
    ],
  },
  {
    id: 'impact-chain-source',
    tag: 'Impact',
    question: 'Is the Impact Chain on a project entered by a person, or generated by the system?',
    answer: [
      'It is a mix, and the Project Detail page now labels each stage so this is never ambiguous:',
      'Inputs and Activities are entered by the project manager or field officer when the project is set up and logged (see Log Activity).',
      'Outputs are aggregated automatically by SPIMS from approved field activity logs — once a manager approves a logged activity, its numbers roll up into the Outputs stage.',
      'Outcomes and Impact are calculated, not measured live — SPIMS applies the stated methodology (tap the ⓘ next to "05 · Impact" to see it) to the Outputs. There is no sensor or survey feeding this in real time.',
      'Every project also carries a note flagging that current figures are Phase 1 illustrative placeholders until Seplat\'s M&E team supplies verified field data.',
    ],
  },
  {
    id: 'standards-library',
    tag: 'Data',
    question: 'What is the Standards Library and how is it different from the Indicator Library?',
    answer: [
      'The Standards Library lists the actual local and global frameworks SPIMS reports against — e.g. NCDMB Nigerian Content Act, PIA Host Community Development Trust, GRI 404/203, IFRS S1 & S2, IPIECA guidance, and the relevant UN SDGs — with a plain-English summary of each.',
      'Each standard shows a worked example: a real project in the portfolio and exactly how that project satisfies the requirement, with a link straight to that project\'s detail page.',
      'The Indicator Library, by contrast, lists the specific measurable indicators (e.g. pupil-teacher ratio, boreholes completed) SPIMS tracks day to day. Standards are the "why we measure this"; indicators are the "what we measure."',
    ],
  },
  {
    id: 'reports-who-uploads',
    tag: 'Reports',
    question: 'Who uploads a report? Is there a standard template? Can I get a report for a single project?',
    answer: [
      'Nobody uploads reports by hand. Every report on the Reports & Exports page is auto-compiled from live SPIMS data using one standardized template per audience (Social Performance Report, ESG/Global, NCDMB/Local compliance, PIA HCDT, SDG contribution, Community feedback).',
      'Click "Preview report" to read the full compiled content in the browser before downloading — this is the same content that goes into the PDF/Excel/Word export.',
      'Yes — reports can also be scoped to a single project. Open any project\'s detail page and use "Download project report" to get a PDF, Excel, or Word export covering just that project\'s inputs, outputs, outcomes, impact and methodology.',
      'PowerPoint export is planned for Phase 2, using Claude to generate slides that keep charts as real graphics instead of flattening everything to text.',
    ],
  },
  {
    id: 'sign-in-roles',
    tag: 'Roles',
    question: 'How do roles and sign-in work?',
    answer: [
      'SPIMS has four personas: Executive (read-only oversight), Project Manager, Field Officer, and Community Relations. Each demo account on the sign-in screen signs in as one of them.',
      'In this prototype, access control is enforced client-side only — a production deployment would enforce these permissions server-side so a Field Officer account could never see Executive screens, and vice versa.',
      'Each role lands on a different default page: Executives land on the Dashboard, Managers on My Projects, Field Officers on My Tasks, and Community Relations on the Stakeholder Register.',
    ],
  },
  {
    id: 'approvals-flow',
    tag: 'Roles',
    question: 'How does the Approvals queue work?',
    answer: [
      'When a Field Officer logs an activity, submits a beneficiary count, records spend, or uploads evidence, it lands in the Approvals queue for a Project Manager to review.',
      'A manager can Approve (which then feeds into that project\'s Outputs) or Return it with a note asking the field officer to fix something. Nothing reaches the Outputs stage of the Impact Chain without going through this approval step.',
    ],
  },
  {
    id: 'targets',
    tag: 'Roles',
    question: 'How do Targets work?',
    answer: [
      'Executives use the Targets page to set a goal for a year or period — e.g. beneficiaries reached, social investment spend, communities covered, or a compliance percentage — and track progress against it.',
      'A target\'s period can span more than one calendar year — some programmes run across multiple years, so the period is a start and end month rather than a fixed financial year.',
      'The progress bar compares current progress to the total target. As with the rest of SPIMS, current-progress figures are illustrative Phase 1 placeholders until they are wired to live field data.',
    ],
  },
  {
    id: 'team-tasks',
    tag: 'Roles',
    question: 'Who creates the tasks that show up on a Field Officer\'s My Tasks page?',
    answer: [
      'The Project Manager does, from the My Team page. A manager invites field officers onto their team, then assigns each task there — title, project, due date, and who it\'s assigned to.',
      'Once assigned, a task appears on that field officer\'s My Tasks list. The field officer can mark it Not started, In progress, or Done — the manager sees that same status update live on My Team, alongside how many tasks each person has and how many they\'ve completed.',
    ],
  },
  {
    id: 'report-comments',
    tag: 'Reports',
    question: 'Can a manager ask for a report to be corrected?',
    answer: [
      'Yes. When a Project Manager previews a report, a Comments section at the bottom lets them leave a note — e.g. flagging a figure that looks wrong — and optionally tick "Request a correction / update".',
      'A report with an open correction request shows a "Needs revision" badge on the Reports & Exports page so it\'s visible at a glance. Comments are visible to anyone who opens the preview.',
    ],
  },
  {
    id: 'data-honesty',
    tag: 'Data',
    question: 'Why do so many numbers say "illustrative" or "Phase 1"?',
    answer: [
      'This build is a design/functional prototype, not connected to Seplat\'s real field data yet. Rather than present placeholder numbers as verified fact, SPIMS labels them honestly wherever they appear — on KPI cards, methodology boxes, and report exports.',
      'When this goes live, those labels are the checklist of exactly what needs a real, sourced data feed before the figure can be presented without caveat.',
    ],
  },
];
