export interface HelpTopic {
  id: string;
  question: string;
  answer: string[];
  tag: 'Data' | 'Roles' | 'Reports' | 'Impact';
}

export const HELP_TOPICS: HelpTopic[] = [
  {
    id: 'lens-toggle',
    tag: 'Data',
    question: 'What does the Local / Global lens toggle on the Executive Dashboard actually do?',
    answer: [
      'It re-frames the same underlying dataset for two different audiences, rather than filtering to different data.',
      'Local shows figures the way Nigerian regulators expect them: NCDMB local content percentages, PIA Host Community Development Trust spend, NUPRC host-community obligations.',
      'Global shows the same activity translated into GRI Standards, IFRS S1/S2 (ISSB) sustainability disclosures, and UN SDG contributions — the language international investors and ESG raters expect.',
      'Both shows every tag side by side so you can see how one project satisfies both audiences at once. Switching lenses changes the KPI subtitles, the budget-breakdown caption, and which tags appear on each outcome row.',
    ],
  },
  {
    id: 'impact-chain-source',
    tag: 'Impact',
    question: 'Is the Impact Chain on a project entered by a person, or generated by the system?',
    answer: [
      'It is a mix, and the Project Detail page now labels each stage so this is never ambiguous:',
      'Inputs and Activities are entered by the project manager or field officer when the project is set up and logged (see Log Activity).',
      'Outputs are aggregated automatically by SPIMS from approved field activity logs — once a manager approves a logged activity, its numbers roll up into the Outputs stage.',
      'Outcomes and Impact are calculated, not measured live — SPIMS applies the stated methodology (shown in the "How this impact figure was calculated" box) to the Outputs. There is no sensor or survey feeding this in real time.',
      'Every project also carries a note flagging that current figures are Phase 1 illustrative placeholders until Seplat\'s M&E team supplies verified field data.',
    ],
  },
  {
    id: 'standards-library',
    tag: 'Data',
    question: 'What is the Standards Library and how is it different from the Indicator Library?',
    answer: [
      'The Standards Library lists the actual local and global frameworks SPIMS reports against — e.g. NCDMB Nigerian Content Act, PIA Host Community Development Trust, GRI 404/203, IFRS S1 & S2, IPIECA guidance, and the relevant UN SDGs — with a plain-English summary of each.',
      'Each standard shows a worked example: a real project in the portfolio and exactly how that project satisfies the requirement, with a link straight to that project\'s detail page.',
      'The Indicator Library, by contrast, lists the specific measurable indicators (e.g. pupil-teacher ratio, boreholes completed) SPIMS tracks day to day. Standards are the "why we measure this"; indicators are the "what we measure."',
    ],
  },
  {
    id: 'reports-who-uploads',
    tag: 'Reports',
    question: 'Who uploads a report? Is there a standard template? Can I get a report for a single project?',
    answer: [
      'Nobody uploads reports by hand. Every report on the Reports & Exports page is auto-compiled from live SPIMS data using one standardized template per audience (Board, ESG/Global, NCDMB/Local compliance, PIA HCDT, SDG contribution, Community feedback).',
      'Click "Preview report" to read the full compiled content in the browser before downloading — this is the same content that goes into the PDF/Excel/Word export.',
      'Yes — reports can also be scoped to a single project. Open any project\'s detail page and use "Download project report" to get a PDF, Excel, or Word export covering just that project\'s inputs, outputs, outcomes, impact and methodology.',
    ],
  },
  {
    id: 'viewing-as',
    tag: 'Roles',
    question: 'What does the "Viewing as" switcher in the top bar do?',
    answer: [
      'SPIMS is a single application with four personas: Executive (read-only oversight), Project Manager, Field Officer, and Community Relations. The switcher lets you preview what each role sees without logging out.',
      'In this prototype the switch is client-side only — a real deployment would enforce these permissions server-side so a Field Officer account could never see Executive screens, and vice versa.',
      'Each role lands on a different default page: Executives land on the Dashboard, Managers on My Projects, Field Officers on My Tasks, and Community Relations on Grievance Cases.',
    ],
  },
  {
    id: 'approvals-flow',
    tag: 'Roles',
    question: 'How does the Approvals queue work?',
    answer: [
      'When a Field Officer logs an activity, submits a beneficiary count, records spend, or uploads evidence, it lands in the Approvals queue for a Project Manager to review.',
      'A manager can Approve (which then feeds into that project\'s Outputs) or Return it with a note asking the field officer to fix something. Nothing reaches the Outputs stage of the Impact Chain without going through this approval step.',
    ],
  },
  {
    id: 'grievances',
    tag: 'Roles',
    question: 'How are community grievances handled?',
    answer: [
      'Community Relations logs a grievance (via Log Grievance), which creates a case. Cases can be assigned, have notes and resolutions added, be escalated if severity warrants it, and closed with a recorded satisfaction rating.',
      'Executives see an aggregated, read-only view of grievance volumes and status on the Grievances page; the case-level detail lives in Grievance Cases, which is scoped to the Community Relations role.',
    ],
  },
  {
    id: 'data-honesty',
    tag: 'Data',
    question: 'Why do so many numbers say "illustrative" or "Phase 1"?',
    answer: [
      'This build is a design/functional prototype, not connected to Seplat\'s real field data yet. Rather than present placeholder numbers as verified fact, SPIMS labels them honestly wherever they appear — on KPI cards, methodology boxes, and report exports.',
      'When this goes live, those labels are the checklist of exactly what needs a real, sourced data feed before the figure can be presented without caveat.',
    ],
  },
];
